### PR TITLE
Add meta tags for app store

### PR DESCRIPTION
**Pull request by rodericj**
Re: #165

### CODE REVIEW

**Comment by rodericj** [comment]
This took me longer than I'm comfortable admitting.

**Comment by rodericj** [comment]
@jamescmartinez I don't know what that failure means. Looks like the db creation step failed.

**Comment by jamescmartinez** [comment]
As the `meta` tag is part of the view, I prefer to keep that logic in the view layer rather than applied via the controller.

Unfortunately, I can't edit your commit since it's a fork on an organization I don't have access to. I've rewritten your commit (and added tests) here: https://github.com/jamescmartinez/coffee/commit/5b51ef1814602eb21032d6f9f32775620db4fb48

**Comment by jamescmartinez** [comment]
This is live on prod.

**Pull request closed without merging**
